language: node_js
node_js:
  - node
  - lts
install:
  - npm install
script:
  - npm test
cache: yarn
deploy:
  provider: npm
  email: "bezgachev@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: production
  skip_cleanup: true